// Generated by scripts/cache-images.mjs. Do not edit.
export const imageMap: Record<string, string> = {
  "https://assets.kivotos.cc/image/2025/05/01/68137fa6a70de.jpg": "/media/news/897d764a65897170.jpg",
  "https://assets.kivotos.cc/image/2025/05/01/68137f9cf1f48.png": "/media/news/8ecb7a6b90f318e0.png",
  "https://assets.kivotos.cc/image/2025/05/01/68137fb192614.jpg": "/media/news/852dd5b369bf377d.jpg",
  "https://assets.kivotos.cc/image/2025/05/01/68137ff194540.png": "/media/news/7f7c61ff4b22140d.png",
  "https://assets.kivotos.cc/image/2025/05/01/68137ffa67186.png": "/media/news/acd56aafe8b41f05.png",
  "https://assets.kivotos.cc/image/2025/05/01/68137fffd1a19.png": "/media/news/7ae2b8fba574195b.png",
  "https://assets.kivotos.cc/image/2025/05/01/68137ffd40a9c.png": "/media/news/faa9264b9cbf052b.png",
  "https://s21.ax1x.com/2024/09/20/pAMSLRJ.png": "/media/news/02882b262ac53ec2.png"
};
